name: Run GRC Scripts

on: [push]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install packages
      run: pip install -r requirements.txt

    - name: Run Incident Simulation
      run: python Scripts/incident-sim.py

    - name: Run Vendor Risk Script
      run: python Scripts/vendor-risk.py
